[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Ensure that your Next.js API routes are treated as Netlify Functions
  included_files = [".next/server/**/*.js", ".next/server/**/*.html", ".next/server/**/*.json"]
